--- Feito pelo hibernate
--- drop table if exists endereco cascade;
--- drop table if exists pessoa cascade;
--- create table endereco (id bigint generated by default as identity, pessoa_id bigint, cidade varchar(255), rua varchar(255), primary key (id));
--- create table pessoa (id bigint generated by default as identity, nome varchar(255), primary key (id));
--- alter table if exists endereco add constraint constraint_chave_estrangeira foreign key (pessoa_id) references pessoa;

INSERT INTO Pessoa (nome) VALUES ('Professor Wellington');
INSERT INTO Pessoa (nome) VALUES ('Professor Xico');
INSERT INTO Endereco (rua, cidade, pessoa_id) VALUES ('Rua da Casa de Wellington, num 15', 'Joanesburgo', SELECT id FROM Pessoa WHERE nome = 'Professor Wellington');
INSERT INTO Endereco (rua, cidade, pessoa_id) VALUES ('Rua do Trabalho de Wellington, num 56456', 'Angicos', SELECT id FROM Pessoa WHERE nome = 'Professor Wellington');
INSERT INTO Endereco (rua, cidade, pessoa_id) VALUES ('Rua da Casa de Xico, num 8987', 'Vienna', SELECT id FROM Pessoa WHERE nome = 'Professor Xico');
INSERT INTO Endereco (rua, cidade, pessoa_id) VALUES ('Rua do Trabalho de Xico, num 9', 'Angicos', SELECT id FROM Pessoa WHERE nome = 'Professor Xico');

--- Exibindo em tabelas separadas
SELECT * FROM Pessoa;
SELECT * FROM Endereco;

--- Experimentando Join
SELECT pes.id AS pessoa_id,
       pes.nome AS pessoa_nome,
       ende.id AS endereco_id,
       ende.rua AS endereco_rua,
       ende.cidade AS endereco_cidade
FROM Pessoa pes
LEFT JOIN Endereco ende ON pes.id = ende.pessoa_id;


--- delete from pessoa;
--- delete from endereco;
--- delete from pessoa;


erDiagram
    PESSOA {
        bigint id PK "Chave Primaria"
        varchar nome "String/Varchar"
    }
    ENDERECO {
        bigint id PK "Chave Primaria"
        varchar rua  "String/Varchar"
        varchar cidade  "String/Varchar"
        bigint pessoa_id FK "Chave Estrangeira"
    }
    
    PESSOA ||--o{ ENDERECO : tem
